const mongoose = require("mongoose");

const messageSchema = new mongoose.Schema(
  {
    sender: { type: mongoose.Schema.Types.ObjectId, ref: "User", required: true },
    receiver: { type: mongoose.Schema.Types.ObjectId, ref: "User", required: true },
    content: { type: String, required: true },
    iv: { type: String, required: true },
    type: { type: String, default: "text" },
    status: { type: String, default: "sent" },
    isEncrypted: { type: Boolean, default: true },

    // 🟢 1. CLIENT ORDERING (Input)
    // Used by Redis to fix network scrambling
    clientId: { type: Number, required: true },
    clientUuid: { type: String, required: true },

    // 🟢 2. SERVER ORDERING (Output) 
    // The "Official" Conversation ID string (e.g., "userA_userB")
    // This matches the _id in your Counter model.
    conversationId: { 
      type: String, 
      required: true 
    },

    // The "Official" Page Number (1, 2, 3...) generated by Counter
    sequenceId: { 
      type: Number, 
      required: true 
    },
  },
  { timestamps: true }
);

// ---------------------------------------------------------
// 🚀 INDEXES
// ---------------------------------------------------------

// 1. DEDUPLICATION SHIELD (Input Side)
// Prevents duplicate "Message #5" from the same session in this conversation.
// We use conversationId here instead of sender/receiver pair -> Simpler!
messageSchema.index({ conversationId: 1, clientUuid: 1, clientId: 1 }, { unique: true });

// 2. CHAT HISTORY SORTING (Output Side)
// "Get me messages for this conversation, sorted by sequence number"
messageSchema.index({ conversationId: 1, sequenceId: -1 });

module.exports = mongoose.model("Message", messageSchema);